### ISSUE TITLE
Not working in windows

### ISSUE THREAD

**Issue by vusaalab** [schneems/get_process_mem#15]
I got an issue when i run this command in windows

        puts mem = GetProcessMem.new.inspect

        Errno::ENOENT: No such file or directory - ps -o rss= -p 3432
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/get_process_mem-     0.2.0/lib/get_process_mem.rb:76:in ``'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/get_process_mem-0.2.0/lib/get_process_mem.rb:76:in `ps_memory'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/get_process_mem-0.2.0/lib/get_process_mem.rb:26:in `bytes'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/get_process_mem-0.2.0/lib/get_process_mem.rb:42:in `inspect'
        from (irb):2
        from C:/Ruby22-x64/bin/irb:11:in `<main>'

**Comment by schneems** [comment]
Looks like we have some options we can shell to `C:\>wmic process where processid=6884 get WorkingSetSize` from http://stackoverflow.com/questions/34769673/get-process-memory-on-windows but it is slow. There's also `$ gem install sys-proctable` and https://github.com/ruby/ruby/blob/trunk/test/lib/memory_status.rb#L18-L61.

I'll need to get my windows machine VM set up again.

**Comment by technogeeky** [comment]
This might be fixed by my patch #19. It seems to work, although derailed_benchmarks does not ever finish.

**Comment by schneems** [comment]
Merged and released 0.2.1 check the readme for directions.
