### ISSUE TITLE
mem variables not exposed

### ISSUE THREAD

**Issue by Silvertale** [schneems/get_process_mem#18]
It looks like the member variables @mb, @kb etc are not exposed. I cannot call them with mem.mb as outlined in readme, but mem.to_json shows that they exist. 

When trying to access mem.mb, I get the following error: `undefined method `mb' for #<String:0x00000000891ca0> (NoMethodError)`

**Comment by schneems** [comment]
They are there https://github.com/schneems/get_process_mem/blob/master/lib/get_process_mem.rb#L30-L40 though they're not variables, they are methods.

Can you give me an example script?

**Comment by Silvertale** [comment]
mem = GetProcessMem.new.inspect
puts("memory usage: " + mem.to_json) <- this works
puts("memory usage: " + mem.mb.to_s) <- this does not exist and throws the above error

**Comment by schneems** [comment]
```
mem = GetProcessMem.new.inspect
```

This will return a string. You're calling `inspect` on the object.

**Comment by Silvertale** [comment]
oh, that makes more sense, it might be good to say that in the readme, its a little unclear since it does say to do `GetProcessMem.new.inspect`

**Comment by schneems** [comment]
Updated, thanks for the note about the readme. Didn't catch the bug until now. Thanks for opening the issue ❤️
