### ISSUE TITLE
Deprecation warning under Ruby 2.5

### ISSUE THREAD

**Issue by aselder** [schneems/get_process_mem#25]
/Users/aselder/.rvm/gems/ruby-2.5.2/gems/get_process_mem-0.2.2/lib/get_process_mem.rb:94: warning: BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.

I'll put together a PR to address this.

**Comment by schneems** [comment]
Thanks, would love a PR!

**Comment by aselder** [comment]
@schneems Here you go: https://github.com/schneems/get_process_mem/pull/26

**Comment by Mehonoshin** [comment]
Looks like this issue can be closed :)

**Comment by schneems** [comment]
Thanks all!
