### ISSUE TITLE
Why is this necessary?

### ISSUE THREAD

**Issue by wonda-tea-coffee** [schneems/get_process_mem#28]
I do not know the intention of this process.
https://github.com/schneems/get_process_mem/blob/master/lib/get_process_mem.rb#L6

When is `BigDecimal.new(value)` able to execute and `BigDecimal(value)` not?

I'm glad if you could tell me... 🙏

**Comment by schneems** [comment]
> When is BigDecimal.new(value) able to execute and BigDecimal(value) not?

Not sure if there ever is a case, feel free to take out the conditional and if the tests all pass, then I can merge it in. I think when it was added we didn't know if there was a version of Ruby it didn't exist in.

**Comment by wonda-tea-coffee** [comment]
Thank you!!! 👍
