### ISSUE TITLE
required ruby version is not compatible with my version

### ISSUE THREAD

**Issue by yovasx2** [schneems/get_process_mem#45]
version 0.2.7 is saying it requires ruby >=0 but it was not installed due to a dependency problem:

```
Fetching: ffi-1.13.1.gem (100%)
ERROR:  Error installing get_process_mem:
	ffi requires Ruby version >= 2.3.
```

please update the .gemspec file

**Comment by schneems** [comment]
That's ffi's issue not ours. There's nothing in this gem that is version specific. You can use a different version of ffi that supports another version of ruby

**Comment by schneems** [comment]
For reference ffi 1.12.x has a dependency on Ruby >= 2.0, you can use that https://rubygems.org/gems/ffi/versions/1.12.2
