### ISSUE TITLE
posix-spawn for ps?

### ISSUE THREAD

**Issue by jjb** [schneems/get_process_mem#47]
idea: switch to posix-spawn for `ps`. Avoids forking the process. Not sure if increases or decreases cpu.

terrapin makes it really easy. if posix-spawn is installed, terrapin will use it as the shell-out method.

```ruby
line = Terrapin::CommandLine.new("ps", "-o rss= -p :pid")
line.run(pid: pid)
```

Not trivial to switch because no easy way to only install terrapin and posix-spawn only when needed. Could check for presence of Module at runtime to decide between terrapin and backtics, and put section in readme explaining benefit of installing terrapin and posix-spawn.

**Comment by schneems** [comment]
Can you write up a benchmark with `benchmark/ips` using the two methods?

In general, we avoid shelling out. On mac, Linux, and windows we **should** never have to shell out. If there's a performance sensitive case where we are shelling out, that's worth talking about.

**Comment by jjb** [comment]
The benchmark would be difficult to make very meaningful because it would vary a lot depending on the app, ruby version, OS version (which influence copy on write performance). posix-spawn has their own time benchmarks: https://github.com/rtomayko/posix-spawn#benchmarks

Good to hear that the `ps` case is very unlikely to happen. Maybe not worth improving that scenario then.
