### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by nathany** [schneems/get_process_mem#9]
I added this to our lograge configuration to log memory usage on every request, but it seems to slow things down a fair bit:

![ruby-time](https://cloud.githubusercontent.com/assets/4566/3414176/c5e1af94-fe12-11e3-8e43-6a25ffe2acf6.png)

``` ruby
config.lograge.custom_options = lambda do |event|
  event.payload.slice(:request_id, :memory_rss)
end
```

``` ruby
# for lograge
def append_info_to_payload(payload)
  super
  # Heroku Request ID https://devcenter.heroku.com/articles/http-request-id
  payload[:request_id] = env['HTTP_X_REQUEST_ID']
  if defined?(GetProcessMem)
    payload[:memory_rss] = "%.2fMB" % GetProcessMem.new.mb
  end
end
```

**Comment by itsderek23** [comment]
Just a quick note: dropping down to c to fetch process memory usage via `getrusage` has yielded very low overhead in my tests.

An example from the [proc-wait3](https://github.com/djberg96/proc-wait3/blob/master/ext/proc/wait3.c#L723) library.

**Comment by schneems** [comment]
Maybe we can load that and use it if its present like multi json.

**Comment by itsderek23** [comment]
Here's some quick benchmarks comparing `GetProcessMem#mb` and `Process#rusage#maxrss` on Ruby 2.1.6p336 and Ubuntu 14.04.2:

<pre>
user     system      total        real
gpm:     6.350000   1.990000   8.340000 (  8.641529)
rusage:  0.000000   0.000000   0.000000 (  0.005222)
</pre>

[The snippet](https://gist.github.com/itsderek23/b9196051f5139820bdce10a86fc8a4c8).

*Downsides*: this would introduce a c-extension and some platform-specific parsing (I believe Darwin reports RSS in bytes).

*Upside*: unless I messed up the benchmark, it's a big improvement and should make it production-safe for most apps.

**Comment by sshaw** [comment]
@itsderek23 this is what I got using your gist on Fedora 20 with 2.1.6 (running under VirtualBox):

```
~/ruby/c5d321df26407f1af3fef419cb49334a >ruby -vI ../get_process_mem/lib rusage.rb 
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
/home/sshaw/ruby/get_process_mem/lib/get_process_mem.rb:52: warning: shadowing outer local variable - line
                 user     system      total        real
gpm:         0.040000   0.040000   0.080000 (  0.080396)
rusage:      0.000000   0.000000   0.000000 (  0.001993)
```

Odd, big difference. Too tired to try on Ubuntu now. I assume most of the time is spent iterating through `/proc/$$/status`'s lines so instead of using `/proc/$$/status` you can use `/proc/$$/statm`. 

Checkout [this commit](https://github.com/sshaw/get_process_mem/commit/aa19497f152930225d89abca83ac0af33afee702) and [benchmarks](https://gist.github.com/sshaw/c5d321df26407f1af3fef419cb49334a). Can you run my version and see what your times are? 

`Ext.getconf` is only available in Ruby >= 2.2 but `getconf` is POSIX copat and I suppose one could default to `4096` in the odd cases where it's not available.

**Comment by sshaw** [comment]
Though really I see no downside to using rusage.

**Comment by sshaw** [comment]
Uh wait, I see why there's a difference, and now I'm totally confused:

```
~/ruby >git cl https://github.com/schneems/get_process_mem.git
Cloning into 'get_process_mem'...
remote: Counting objects: 158, done.
remote: Total 158 (delta 0), reused 0 (delta 0), pack-reused 158
Receiving objects: 100% (158/158), 24.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (62/62), done.
Checking connectivity... done.
~/ruby >cd get_process_mem/
~/ruby/get_process_mem >git lr
2015-08-06 10:28:58 -0500 c7722a0 Richard Schneeman	master
2015-08-06 10:28:58 -0500 c7722a0 Richard Schneeman	origin/HEAD
2015-08-06 10:28:58 -0500 c7722a0 Richard Schneeman	origin/master
2014-06-16 14:19:18 -0500 f063569 schneems	origin/schneems/revert-to-rss
2014-04-07 00:30:23 -0400 17e6b9a schneems	origin/schneems/swap-linux
~/ruby/get_process_mem >git tag
~/ruby/get_process_mem >gem list -r get_process_mem

*** REMOTE GEMS ***

get_process_mem (0.2.0)
get_process_mem-1-8-7 (0.3.1)
~/ruby/get_process_mem >cd /tmp
/tmp >gem unpack get_process_mem
Fetching: get_process_mem-0.2.0.gem (100%)
Unpacked gem: '/private/tmp/get_process_mem-0.2.0'
/tmp >diff get_process_mem-0.2.0/lib/get_process_mem/version.rb  ~/ruby/get_process_mem/lib/get_process_mem/version.rb
2c2
<   VERSION = "0.2.0"
---
>   VERSION = "0.1.1"
/tmp >diff get_process_mem-0.2.0/lib/get_process_mem.rb  ~/ruby/get_process_mem/lib/get_process_mem.rb
14a15
>     @status_file  = Pathname.new "/proc/#{pid}/status"
17c18
<     @linux        = @process_file.exist?
---
>     @linux        = @status_file.exist?
25c26
<     memory =   linux_memory if linux?
---
>     memory =   linux_status_memory if linux?
46,51c47,55
<   def mem_type
<     @mem_type
<   end
<
<   def mem_type=(mem_type)
<     @mem_type = mem_type.downcase
---
>   # linux stores memory info in a file "/proc/#{pid}/status"
>   # If it's available it uses less resources than shelling out to ps
>   def linux_status_memory(file = @status_file)
>     line = file.each_line.detect {|line| line.start_with? 'VmRSS'.freeze }
>     return unless line
>     return unless (_name, value, unit = line.split(nil)).length == 3
>     CONVERSION[unit.downcase!] * value.to_i
>   rescue Errno::EACCES, Errno::ENOENT
>     0
54,55c58
<   # linux stores memory info in a file "/proc/#{pid}/smaps"
<   # If it's available it uses less resources than shelling out to ps
---
>   # linux stores detailed memory info in a file "/proc/#{pid}/smaps"
57c60
<     lines = file.each_line.select {|line| line.match /^Rss/ }
---
>     lines = file.each_line.select {|line| line.match(/^Rss/) }
71,72d73
<   private
<
77a79
>
```

Where's the source repo for the latest version @schneems?

**Comment by schneems** [comment]
https://github.com/schneems/get_process_mem/commit/ed81d8fece7888be1a9f28a4a0f1335ea4195dc0 Is the commit for 0.2.0 which is accidentally labled 0.2.1 in the changelog. You can do a git blame of the changelog. 

I've started tagging releases in all  my gems, but this was before that.

**Comment by sshaw** [comment]
@schneems you should have a second look because whatever is part of v0.2.0 is not in the repo. Looks like it was pushed to RubyGems but never :octocat::

```
~/ruby/get_process_mem >git co ed81d8fe
Note: checking out 'ed81d8fe'.
<snip git warning>
HEAD is now at ed81d8f... revert back to RSS until #7 is solved
~/ruby/get_process_mem >diff -r lib /tmp/get_process_mem-0.2.0/lib/
diff -r lib/get_process_mem/version.rb /tmp/get_process_mem-0.2.0/lib/get_process_mem/version.rb
2c2
<   VERSION = "0.1.1"
---
>   VERSION = "0.2.0"
diff -r lib/get_process_mem.rb /tmp/get_process_mem-0.2.0/lib/get_process_mem.rb
20,30d19
<   def self.all
<     if proc = Pathname.new("/proc").exist?
<       proc.each_entry.map do |entry|
<         smap = entry.join("smaps")
<         linux_memory_from_smap(smap) if smap.exist?
<       end.reduce(:+)
<     else
<
<     end
<   end
<
```

**Comment by schneems** [comment]
```
2.3.0  ~/documents/projects/get_process_mem (master)
$ git push
Everything up-to-date
```

Everything i've got locally is on github.

**Comment by sshaw** [comment]
Well can you explain the above diff?

**Comment by schneems** [comment]
It looks like I didn't push the version change. Must changed it, pushed to rubygems and not committed it. That was about 2 years ago. I've since gotten a new computer. 

Checked with my backup files and looks like I never pushed https://github.com/schneems/get_process_mem/pull/17 (which I just did). Must have deployed from that branch by mistake and never pushed.

Not sure about the `self.all` stuff.

**Comment by sshaw** [comment]
Great!

The `schneems/linux-all` branch is v0.2.0 but master is not -nevertheless, discrepancies aside, master does not suffer from the speed issues outlined by @itsderek23 and @nathany.

**Comment by schneems** [comment]
I'll cut a release from master soon and be sure to tag it this time.

**Comment by schneems** [comment]
This has been merged and deployed a long time ago also there's some fixes for mac speed recently with a 20x plus perf improvement.
